import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import '~/app/globals.css'
import { Toaster } from '~/components/ui/sonner'
import { cn } from '~/lib/utils'

const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: '300',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(publicSans.className)}>
        <Toaster
          position="top-center"
          closeButton
          toastOptions={{
            duration: 5000,
            classNames: {
              success: 'text-green-500 bg-background border-none capitalize',
              error: 'text-red-500 bg-background border-none capitalize',
            },
          }}
        />
        {children}
      </body>
    </html>
  )
}
